import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:'export * from "./lib/assembly";export {generateRecipe} from "./lib/models";',resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const {assemblyTracks,assemblyPose,generateRecipe}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const model=generateRecipe('bridge','small');
test('every catalog piece reaches its exact original transform before the final hold',()=>{const source=JSON.stringify(model.pieces),tracks=assemblyTracks(model.pieces,model.length,model.width,model.height);assert.equal(tracks.size,model.pieces.length);for(const p of model.pieces){assert.deepEqual(assemblyPose(tracks.get(p.id),1),{x:0,y:0,z:0,rx:0,ry:0,rz:0,scale:1,settled:true});assert.equal(assemblyPose(tracks.get(p.id),.901).settled,true);}assert.equal(JSON.stringify(model.pieces),source);});
test('lower layers start before higher layers and replay/seek is deterministic',()=>{const a=assemblyTracks(model.pieces,model.length,model.width,model.height),b=assemblyTracks(model.pieces,model.length,model.width,model.height);const sorted=[...model.pieces].sort((p,q)=>p.y-q.y||p.stage-q.stage||p.z-q.z||p.x-q.x||p.id-q.id);for(let i=1;i<sorted.length;i++)assert.ok(a.get(sorted[i].id).start>=a.get(sorted[i-1].id).start);for(const piece of sorted){assert.deepEqual(assemblyPose(a.get(piece.id),.42),assemblyPose(b.get(piece.id),.42));for(const time of [0,.1,.3,.6,.9,1]){const pose=assemblyPose(a.get(piece.id),time);for(const [key,value] of Object.entries(pose))if(key!=='settled')assert.ok(Number.isFinite(value));assert.ok(pose.scale>=0&&pose.scale<=1);assert.ok(pose.y>=0);}}});
test('empty and single-piece models have finite, reversible timelines',()=>{assert.equal(assemblyTracks([],0,0,0).size,0);const piece=model.pieces[0],track=assemblyTracks([piece],1,1,1).get(piece.id);const waiting=assemblyPose(track,0);assert.equal(waiting.scale,1);assert.equal(waiting.settled,false);assert.ok(Math.hypot(waiting.x,waiting.z)>0,"a brick waits at the far end of its path from the first frame");assert.equal(assemblyPose(track,1).settled,true);const middle=assemblyPose(track,track.start+.1);assert.ok(middle.scale>0);assert.ok(middle.y>0);assert.deepEqual(assemblyPose(track,track.start+.1),middle);});
