import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
const result=await build({stdin:{contents:'export * from "./lib/generated-scene";export * from "./lib/generation-provider";export * from "./lib/generation-stream";export {auditModel,partsCSV,ldrawFile} from "./lib/bridge";',resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const withIds=scene=>({...scene,shapes:scene.shapes.map(s=>({...s,id:s.id||s.label,component:s.component||s.label,end:s.end||{x:0,y:0,z:0},radius:s.radius??1,repeat:s.repeat||{count:1,offset:{x:0,y:0,z:0}}}))});
const {compileScene,sceneVoxels,validateScene,SceneStreamParser,generateScene,readEvents,auditModel,partsCSV,ldrawFile,compactScene,expandCompactShape}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const shape=(label,kind,color,position,size,extra={})=>({label,kind,color,position,size,operation:'add',end:{x:0,y:0,z:0},radius:1,...extra});
const violin={name:'Violin with a bow',description:'A violin sculpture with a neck, bridge and bow.',dimensions:{x:28,y:16,z:16},shapes:[shape('Display base','box','gray',{x:0,y:0,z:0},{x:28,y:2,z:16}),shape('Violin body','ellipsoid','brown',{x:4,y:2,z:3},{x:11,y:8,z:10}),shape('Neck','box','tan',{x:14,y:4,z:7},{x:9,y:3,z:2}),shape('Bridge','box','black',{x:10,y:9,z:6},{x:1,y:2,z:4}),shape('Bow','beam','tan',{x:3,y:4,z:1},{x:1,y:1,z:1},{end:{x:24,y:4,z:2},radius:.7})]};
function providerStream(scene,{completed=true,fragment=53}={}){const text=JSON.stringify(compactScene(scene)),frames=[];for(let i=0;i<text.length;i+=fragment)frames.push({type:'response.output_text.delta',delta:text.slice(i,i+fragment)});if(completed)frames.push({type:'response.completed',response:{status:'completed'}});const bytes=new TextEncoder().encode(frames.map(x=>'data: '+JSON.stringify(x)+'\r\n\r\n').join(''));return new ReadableStream({start(controller){for(let i=0;i<bytes.length;i+=17)controller.enqueue(bytes.slice(i,i+17));controller.close();}});}
async function collect(generator){const out=[];for await(const e of generator)out.push(e);return out;}
test('custom subject compiles into non-overlapping catalog pieces and matching exports',()=>{const model=compileScene(violin),voxels=sceneVoxels(violin);assert.equal(model.source,'custom');assert.equal(model.recipe,undefined);assert.equal(model.pieces.reduce((n,p)=>n+p.w*p.h*p.d,0),voxels.size);assert.equal(model.inventory.reduce((n,r)=>n+r.quantity,0),model.pieces.length);assert.equal(auditModel(model.pieces).overlaps,0);assert.equal(partsCSV(model.inventory,{},{}).trim().split('\n').length,model.inventory.length+1);assert.equal(ldrawFile(model.pieces,model.name,model.stages).split('\n').filter(line=>line.startsWith('1 ')).length,model.pieces.length);});
test('ordered subtraction carves space and later additions recolor it',()=>{const s={...violin,shapes:[shape('block','box','red',{x:0,y:0,z:0},{x:4,y:4,z:4}),shape('hole','box','black',{x:1,y:1,z:1},{x:2,y:2,z:2},{operation:'subtract'}),shape('detail','box','blue',{x:1,y:1,z:1},{x:1,y:1,z:1})]};const v=sceneVoxels(s);assert.equal(v.size,57);assert.equal(v.get('1,1,1'),'blue');assert.equal(v.has('2,2,2'),false);});
test('beam calculations use physical plate height',()=>{const v=sceneVoxels({...violin,shapes:[shape('vertical beam','beam','tan',{x:8,y:4,z:8},{x:1,y:1,z:1},{end:{x:8,y:8,z:8},radius:2})]});assert.equal(v.has('7,0,7'),true);assert.equal(v.has('7,13,7'),false);});
test('rejects oversized work, bad colors, non-finite geometry, outside bounds and empty scenes',()=>{assert.throws(()=>validateScene({...violin,shapes:[{...violin.shapes[0],color:'constructor'}]}));assert.throws(()=>validateScene({...violin,shapes:[{...violin.shapes[0],position:{x:Infinity,y:0,z:0}}]}));assert.throws(()=>validateScene({...violin,shapes:[{...violin.shapes[0],size:{x:64,y:120,z:64}}]}));const huge={...violin,dimensions:{x:64,y:120,z:64},shapes:Array.from({length:10},()=>shape('expensive subtraction','box','gray',{x:0,y:0,z:0},{x:64,y:120,z:64},{operation:'subtract'}))};assert.throws(()=>validateScene(huge),/complex/);assert.throws(()=>compileScene({...violin,shapes:[{...violin.shapes[0],operation:'subtract'}]}),/empty/);});
test('JSON parser emits complete shapes safely across single-character chunks',()=>{const scene={...violin,description:'A "quoted" violin {with braces} 🎻',shapes:violin.shapes.map(s=>({...s,label:s.label+' {"x"}'}))};const parser=new SceneStreamParser();for(const char of JSON.stringify(compactScene(scene)))parser.push(char);assert.deepEqual(parser.finish(),{header:{name:scene.name,description:scene.description,dimensions:scene.dimensions},removed:[],shapes:withIds(scene).shapes});assert.equal(parser.shapes.length,scene.shapes.length);});
test('real provider contract streams original geometry and forwards refinement context',async()=>{let body;const events=await collect(generateScene({prompt:'Add a bow to this violin',detail:'small',previous:violin},'test-key','test-model',new AbortController().signal,async(url,request)=>{assert.equal(url,'https://api.openai.com/v1/responses');body=JSON.parse(request.body);assert.equal(request.headers.Authorization,'Bearer test-key');return new Response(providerStream(violin));}));assert.deepEqual(body.input&&JSON.parse(body.input[0].content[0].text).previous,compactScene(violin));assert.equal(body.store,false);assert.equal(body.stream,true);assert.equal(body.text.format.strict,true);assert.equal(events.filter(e=>e.type==='shape').length,violin.shapes.length);assert.equal(events.at(-1).type,'complete');assert.deepEqual(events.at(-1).scene,withIds(violin));});
test('no fake completion when upstream disconnects or rejects credentials',async()=>{await assert.rejects(()=>collect(generateScene({prompt:'A violin',detail:'small'},'test-key','test-model',new AbortController().signal,async()=>new Response(providerStream(violin,{completed:false})))),/before the model finished/);await assert.rejects(()=>collect(generateScene({prompt:'A violin',detail:'small'},'test-key','test-model',new AbortController().signal,async()=>new Response('',{status:401}))),/API key/);});
test('cancellation is forwarded to the AI service',async()=>{const abort=new AbortController();abort.abort();await assert.rejects(()=>collect(generateScene({prompt:'A violin',detail:'small'},'test-key','test-model',abort.signal,async(_url,request)=>{assert.equal(request.signal,abort.signal);request.signal.throwIfAborted();})),{name:'AbortError'});});

const routeBundle=await build({stdin:{contents:'export {GET,POST} from "./app/api/generate/route";',resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'test-only-empty-worker-env',setup(builder){builder.onResolve({filter:/^cloudflare:workers$/},()=>({path:'worker-env',namespace:'test-fixture'}));builder.onLoad({filter:/.*/,namespace:'test-fixture'},()=>({contents:'export const env = {};',loader:'js'}));}}]});
const {GET,POST}=await import('data:text/javascript;base64,'+Buffer.from(routeBundle.outputFiles[0].text).toString('base64'));
test('unconfigured service reports setup explicitly and never produces a pretend model',async()=>{assert.deepEqual(await (await GET(new Request('https://brickwork.test/api/generate'))).json(),{configured:false,budgetLimit:10});const response=await POST(new Request('https://brickwork.test/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'A violin',detail:'small'})}));assert.equal(response.status,503);assert.equal((await response.json()).code,'AI_NOT_CONNECTED');});
test('generation endpoint rejects cross-origin requests and malformed input before billing',async()=>{const cross=await POST(new Request('https://brickwork.test/api/generate',{method:'POST',headers:{origin:'https://unrelated.test','x-brickwork-api-key':'test-only-key'},body:'{}'}));assert.equal(cross.status,403);const malformed=await POST(new Request('https://brickwork.test/api/generate',{method:'POST',headers:{'x-brickwork-api-key':'test-only-key'},body:JSON.stringify({prompt:'A violin',detail:'medium',previous:{arbitrary:'code'}})}));assert.equal(malformed.status,400);});
test('compact shapes are read leniently and a bad shape mid-stream still settles usage before failing',async()=>{
 const box=expandCompactShape({i:'b',c:'B',l:'box',k:'box',o:'add',a:'x',col:'red',p:[0,0,0],s:[4,4,4],e:[1,1,1],r:0,rep:[1,0,0,0]});
 assert.equal(box.radius,1);assert.equal(box.axis,undefined);assert.equal(box.repeat.count,1);
 const beam=expandCompactShape({i:'w',c:'W',l:'beam',k:'beam',o:'add',a:null,col:'red',p:[0,0,0],s:[9,9,9],e:[4,0,0],r:40,rep:null});
 assert.equal(beam.radius,12);assert.deepEqual(beam.size,{x:1,y:1,z:1});
 const bad=JSON.stringify({n:'x',d:'',dim:[8,8,8],rm:[],sh:[{i:'a',c:'A',l:'a',k:'box',o:'add',a:null,col:'purple',p:[0,0,0],s:[2,1,1],e:null,r:null,rep:null}]});
 const frames=[{type:'response.output_text.delta',delta:bad},{type:'response.completed',response:{status:'completed',usage:{input_tokens:100,output_tokens:50}}}];
 let usage=null;const fetcher=async()=>new Response(frames.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''));
 await assert.rejects(async()=>{for await(const _ of generateScene({prompt:'x',detail:'small'},'k','m',new AbortController().signal,fetcher,async u=>{usage=u;})){}},{code:'INVALID_GEOMETRY'});
 assert.deepEqual(usage,{input_tokens:100,output_tokens:50});
});
test('out-of-range compact coordinates are clamped, and a schema failure names the field',()=>{
 const s=expandCompactShape({i:'q',c:'Q',l:'q',k:'box',o:'add',a:null,col:'red',p:[95,-3,4],s:[200,4,4],e:null,r:null,rep:null});
 assert.deepEqual(s.position,{x:80,y:0,z:4});assert.equal(s.size.x,80);
 assert.throws(()=>expandCompactShape({i:'q',c:'Q',l:'q',k:'box',o:'add',a:null,col:'purple',p:[0,0,0],s:[1,1,1],e:null,r:null,rep:null}));
});
