"use client";
import {useEffect,useId,useState} from "react";
import {ArrowRight,Box,Upload,ImageIcon,FileBox,Plus,Sparkles,LoaderCircle} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Progress} from "@/components/ui/progress";
import {COLORS} from "@/lib/bridge";
import type {ColorKey,Config} from "@/lib/bridge";
import {RECIPES,generateRecipe,parseIdea,mosaicFromPixels,validateProject} from "@/lib/models";
import type {BuildModel,Recipe,Detail} from "@/lib/models";

export type Creation={model:BuildModel;detail:Detail;color:ColorKey;accent:ColorKey;bridgeConfig?:Config;applied?:string[]};
export function IdeaBar({onGenerate,onOpen,compact=false,inline=false}:{onGenerate:(prompt:string)=>void;onOpen:()=>void;compact?:boolean;inline?:boolean}){
 const inputId=useId(),[prompt,setPrompt]=useState("");
 if(inline)return <form className="quick-create" onSubmit={e=>{e.preventDefault();if(prompt.trim().length>=3)onGenerate(prompt);}}><label htmlFor={inputId}>Make something of your own</label><div className="quick-create-field"><input id={inputId} placeholder="A dragon around a castle…" maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)}/><button type="submit" disabled={prompt.trim().length<3} aria-label="Create a build from your idea"><Sparkles size={17}/><span>Create</span><ArrowRight size={16}/></button><button className="quick-import" type="button" onClick={onOpen} aria-label="Import an image, 3D model or project"><Upload size={18}/></button></div></form>;
 return <section className={compact?"idea-bar idea-bar-dialog":"idea-bar"}>
 {!compact&&<div className="idea-heading"><div><h2>Create your own build</h2></div><button className="button secondary" onClick={onOpen}><Upload size={16}/><span>More ways to create</span></button></div>}
 <form onSubmit={e=>{e.preventDefault();if(prompt.trim().length>=3)onGenerate(prompt);}} className="create-idea-form">
 <label htmlFor={inputId}>Describe what you want to build</label><textarea id={inputId} autoFocus={compact} placeholder="A green dragon wrapped around a tower, with gold horns…" maxLength={2000} rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)}/>
 <button className="button primary" type="submit" disabled={prompt.trim().length<3}><Sparkles size={17}/><span>Shape my brief</span><ArrowRight size={17}/></button>
 </form><div className="idea-suggestions"><span>TRY AN IDEA</span>{[{label:"Dragon",prompt:"A green dragon curled around a medieval tower with gold horns"},{label:"Record player",prompt:"A retro orange record player with a black vinyl record and silver tonearm"},{label:"Astronaut",prompt:"An astronaut tending a tiny garden on the moon"}].map(idea=><button key={idea.label} onClick={()=>setPrompt(idea.prompt)}>{idea.label}<Plus size={12}/></button>)}</div>
 <p className="idea-help">Next: choose scale, detail and must-have features. Then watch your design take shape.</p></section>;
}
export default function CreateBuild({open,onOpenChange,onCreate,onGenerate}:{open:boolean;onOpenChange:(open:boolean)=>void;onCreate:(creation:Creation)=>void;onGenerate:(prompt:string,image?:string)=>void}){
 const [tab,setTab]=useState("describe"),[detail,setDetail]=useState<Detail>("large"),[color,setColor]=useState<ColorKey>("white"),[file,setFile]=useState<File|null>(null),[resolution,setResolution]=useState("24"),[axis,setAxis]=useState<"y"|"z">("y"),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState("");
 useEffect(()=>{if(open){setTab("describe");setError("");setFile(null);}},[open]);
 const accept=tab==="image"?"image/png,image/jpeg,image/webp":tab==="mesh"?".stl,.obj":".json";
 function changeTab(t:string){setTab(t);setFile(null);setError("");setResolution(t==="image"?"48":"24");}
 async function starter(recipe:Recipe){setBusy(true);setError("");await new Promise(r=>setTimeout(r,0));try{const r=RECIPES.find(r=>r.id===recipe)!,parsed=parseIdea(r.prompt),accent="error" in parsed?"white":parsed.accent;onCreate({model:generateRecipe(recipe,detail,r.color,accent),detail,color:r.color,accent});onOpenChange(false);}catch(e){setError(e instanceof Error?e.message:"Unable to make this model.");}finally{setBusy(false);}}
 async function sculpt(){if(!file)return;setBusy(true);setError("");try{const imports=await import("@/lib/imports");const image=await imports.imageDataURL(file);onOpenChange(false);onGenerate(`Recreate the subject of this photo as a brick sculpture, true to its shape, colors and details.`,image);}catch(e){setError(e instanceof Error?e.message:"This photo could not be prepared.");}finally{setBusy(false);}}
 async function convert(){if(!file)return;setBusy(true);setError("");setProgress(0);try{let model:BuildModel;if(tab==="project"){if(file.size>12*1024*1024)throw Error("Choose a project smaller than 12 MB.");model=validateProject(JSON.parse(await file.text()));}else{const imports=await import("@/lib/imports");if(tab==="image"){const pixels=await imports.imagePixels(file,Number(resolution));model=mosaicFromPixels(pixels.data,pixels.width,pixels.height,file.name.replace(/\.[^.]+$/, ""));}else model=await imports.meshToBricks(file,Number(resolution),color,axis,setProgress);}onCreate({model,detail:model.detail||detail,color:model.primary||color,accent:model.accent||"white"});onOpenChange(false);}catch(e){setError(e instanceof Error?e.message:"This file couldn't be converted. Try a different file.");}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!busy)onOpenChange(v);}}><DialogContent className="create-dialog"><DialogHeader><DialogTitle>Create your own build</DialogTitle><DialogDescription>Type an idea below, or choose another way to start.</DialogDescription></DialogHeader><Tabs value={tab} onValueChange={changeTab}><TabsList className="create-tabs"><TabsTrigger value="describe" disabled={busy}><Sparkles size={15}/>Idea</TabsTrigger><TabsTrigger value="starters" disabled={busy}><Box size={15}/>Presets</TabsTrigger><TabsTrigger value="image" disabled={busy}><ImageIcon size={15}/>Image</TabsTrigger><TabsTrigger value="mesh" disabled={busy}><FileBox size={15}/>3D model</TabsTrigger><TabsTrigger value="project" disabled={busy}><Upload size={15}/>Project</TabsTrigger></TabsList><TabsContent value="describe"><IdeaBar compact onGenerate={prompt=>{onOpenChange(false);onGenerate(prompt);}} onOpen={()=>changeTab("image")}/><div className="creation-alternatives"><button className="button secondary" onClick={()=>changeTab("image")}><ImageIcon size={16}/>Upload image</button><button className="button secondary" onClick={()=>changeTab("mesh")}><FileBox size={16}/>Import 3D model</button><button className="button secondary" onClick={()=>void starter("blank")} disabled={busy}><Plus size={16}/>Start blank</button></div></TabsContent><TabsContent value="starters"><div className="starter-top"><p>Choose a design to make it your own.</p><Select value={detail} onValueChange={v=>setDetail(v as Detail)} disabled={busy}><SelectTrigger aria-label="Starting design size"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="small">Small</SelectItem><SelectItem value="medium">Medium</SelectItem><SelectItem value="large">Large</SelectItem></SelectContent></Select></div><div className="starter-grid">{RECIPES.map((r,i)=><button key={r.id} onClick={()=>void starter(r.id)} disabled={busy}><span className="starter-number" style={{color:COLORS[r.color].hex}}>{r.id==="blank"?<Plus size={23}/>:String(i+1).padStart(2,"0")}</span><strong>{r.name}</strong><span>{r.description}</span><ArrowRight size={15}/></button>)}</div></TabsContent>
 <TabsContent value="image"><div className="import-copy"><h3>Any photo. A real sculpture.</h3><p>Choose a picture and the builder studies it and sculpts what it shows in bricks, using your AI budget. Or make a flat, studded mosaic in the 12-color palette without AI.</p></div></TabsContent>
 <TabsContent value="mesh"><div className="import-copy"><h3>Bring a shape. Build it in bricks.</h3><p>Convert an STL or OBJ into a solid brick sculpture on a display base. Use a closed mesh under 10 MB and 60,000 triangles. Fine details and moving mechanisms become a simplified sculpture.</p></div></TabsContent>
 <TabsContent value="project"><div className="import-copy"><h3>Pick up where you left off.</h3><p>Open a project JSON exported from Brickwork. Restore your design brief, AI revisions, protected brick edits and shopping notes alongside the model.</p></div></TabsContent></Tabs>
 {["image","mesh","project"].includes(tab)&&<div className="import-form"><label className={"file-drop "+(file?"has-file":"")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0]){setFile(e.dataTransfer.files[0]);setError("");}}}><Upload size={24}/><strong>{file?file.name:tab==="image"?"Choose an image":tab==="mesh"?"Choose an STL or OBJ":"Choose a Brickwork project"}</strong><span>{file?`${(file.size/1024).toFixed(0)} KB · Click to change`:"Click to browse, or drop your file here"}</span><input type="file" accept={accept} disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setError("");}} aria-label="File to convert"/></label>
 {tab!=="project"&&<div className="import-options"><div><label>Resolution</label><Select value={resolution} onValueChange={setResolution} disabled={busy}><SelectTrigger aria-label="Conversion resolution"><SelectValue/></SelectTrigger><SelectContent>{(tab==="image"?[24,48,72,96]:[16,24,32]).map(n=><SelectItem key={n} value={String(n)}>{n} studs · {n*.8} cm longest side</SelectItem>)}</SelectContent></Select></div>{tab==="mesh"&&<><div><label>Model color</label><Select value={color} onValueChange={v=>setColor(v as ColorKey)} disabled={busy}><SelectTrigger aria-label="Converted model color"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(COLORS).map(([k,c])=><SelectItem key={k} value={k}>{c.name}</SelectItem>)}</SelectContent></Select></div><div><label>Up direction</label><Select value={axis} onValueChange={v=>setAxis(v as "y"|"z")} disabled={busy}><SelectTrigger aria-label="3D model up direction"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="y">Y up · common for OBJ</SelectItem><SelectItem value="z">Z up · common for STL</SelectItem></SelectContent></Select></div></>}</div>}
 <p className="import-private">Your file is processed in this browser.</p>{busy&&<div className="import-progress"><Progress value={progress}/><span>{tab==="mesh"?`${progress}% · Converting your shape` :"Making your model…"}</span></div>}{tab==="image"?<div className="import-actions"><button className="button primary import-submit" disabled={busy||!file} onClick={()=>void sculpt()}>{busy?<LoaderCircle size={17} className="spin"/>:<Sparkles size={17}/>}Sculpt it with AI</button><button className="button secondary" disabled={busy||!file} onClick={()=>void convert()}>Make a flat mosaic</button></div>:<button className="button primary import-submit" disabled={busy||!file} onClick={()=>void convert()}>{busy?<LoaderCircle size={17} className="spin"/>:<Box size={17}/>} {busy?"Building…":tab==="project"?"Open project":"Turn it into bricks"}</button>}</div>}
 {error&&<p className="creation-error" role="alert">{error}</p>}
 </DialogContent></Dialog>;
}
