"use client";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Switch} from "@/components/ui/switch";
import type {DesignBrief} from "@/lib/design-project";
export default function BriefForm({brief,onChange}:{brief:DesignBrief;onChange:(brief:DesignBrief)=>void}){
 const change=(patch:Partial<DesignBrief>)=>onChange({...brief,...patch});
 return <div className="brief-form"><label htmlFor="brief-idea">What are we making?</label><Textarea id="brief-idea" rows={3} value={brief.idea} maxLength={2000} onChange={e=>change({idea:e.target.value})} placeholder="A dragon curled around a ruined tower, with gold horns and a tiny library inside…"/>
 <fieldset><legend>Choose your scale</legend><RadioGroup value={brief.size} onValueChange={v=>{const size=v as DesignBrief["size"],preset=size==="small"?{maxWidth:16,maxDepth:16,maxHeight:40,maxPieces:200}:size==="medium"?{maxWidth:24,maxDepth:24,maxHeight:64,maxPieces:600}:{maxWidth:48,maxDepth:40,maxHeight:120,maxPieces:4000};change({size,...preset});}} className="brief-options">{[{id:"small",name:"Desk",text:"Up to 200 pieces"},{id:"medium",name:"Shelf",text:"Up to 600 pieces"},{id:"large",name:"Statement",text:"Up to 4,000 pieces"}].map(o=><label key={o.id} className={brief.size===o.id?"chosen":""}><RadioGroupItem value={o.id}/><strong>{o.name}</strong><span>{o.text}</span></label>)}</RadioGroup></fieldset>
 <details className="brief-personalize"><summary><span>Make it more personal</span><small>{brief.detail==="signature"?"Signature":brief.detail==="balanced"?"Essential":"Detailed"} · {brief.features.filter(Boolean).length?`${brief.features.filter(Boolean).length} required details`:"Optional"}</small></summary><div>
 <fieldset><legend>How much detail?</legend><RadioGroup value={brief.detail} onValueChange={v=>change({detail:v as DesignBrief["detail"]})} className="brief-options">{[{id:"balanced",name:"Essential",text:"Clean forms"},{id:"detailed",name:"Detailed",text:"Texture & character"},{id:"signature",name:"Signature",text:"Intricate layers"}].map(o=><label key={o.id} className={brief.detail===o.id?"chosen":""}><RadioGroupItem value={o.id}/><strong>{o.name}</strong><span>{o.text}</span></label>)}</RadioGroup><p className="field-help">Signature adds surface detail and repeated motifs. Allow more time and pieces for intricate builds.</p></fieldset>
 <label htmlFor="brief-features">Details that must be there <span>Optional, one per line</span></label><Textarea id="brief-features" rows={3} value={brief.features.join("\n")} maxLength={1920} onChange={e=>change({features:e.target.value.split("\n").slice(0,12)})} placeholder={"Gold horns\nA spiral staircase\nAn open library window"}/>
 <details className="brief-advanced"><summary>Fine-tune limits and style</summary><div className="brief-dimensions">{([{key:"maxWidth",label:"Width · studs",max:80},{key:"maxDepth",label:"Depth · studs",max:80},{key:"maxHeight",label:"Height · plates",max:160}] as const).map(f=><label key={f.key}>{f.label}<Input type="number" value={brief[f.key]} min={16} max={f.max} onChange={e=>change({[f.key]:Number(e.target.value)})}/></label>)}</div><label htmlFor="brief-pieces">Maximum pieces</label><Input id="brief-pieces" type="number" min={100} max={16000} step={100} value={brief.maxPieces} onChange={e=>change({maxPieces:Number(e.target.value)})}/><label htmlFor="brief-style">Design style</label><Input id="brief-style" value={brief.style} maxLength={120} onChange={e=>change({style:e.target.value})}/><div className="brief-switch"><div><label htmlFor="brief-hollow">Hollow large interiors</label><p>Keep exterior walls and internal ribs. Support paths are checked again.</p></div><Switch id="brief-hollow" checked={brief.hollow} onCheckedChange={hollow=>change({hollow})}/></div></details></div></details></div>;
}
