"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowRight,Check,LoaderCircle,RotateCcw,Send,Square,Sparkles,LockKeyhole,Eye,Play,Pause,SlidersHorizontal,Maximize2,ShoppingBag} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import AIConnection from "./ai-connection";
import type {BudgetSnapshot} from "@/lib/ai-budget";
import {Textarea} from "@/components/ui/textarea";
import {Checkbox} from "@/components/ui/checkbox";
import Viewport from "./viewport";
import {saveDesign,packDesign,newDesignId} from "@/lib/design-library";
import type {ReferenceSheet} from "@/lib/design-research";
import {targetExtents,shellPlan} from "@/lib/design-research";
import type {MassingCritique} from "@/lib/design-review";
import BriefForm from "./design-brief";
import {normalizeScene,componentBudget} from "@/lib/generated-scene";
import {PreviewQueue,foundationScene} from "@/lib/live-arrivals";
import {readEvents} from "@/lib/generation-stream";
import {canKeepPartial,continuationPrompt} from "@/lib/generation-recovery";
import {GenerationError,generationFailure} from "@/lib/generation-errors";
import {briefSchema,defaultBrief,emptyManual,designChecks,sceneDiff} from "@/lib/design-project";
import type {DesignBrief,VisualReview,ManualEdits} from "@/lib/design-project";
import type {GeneratedScene,SceneHeader,Shape} from "@/lib/generated-scene";
import type {BuildModel} from "@/lib/models";
import type {Creation} from "./create-build";
type Props={open:boolean;onOpenChange:(open:boolean)=>void;initialPrompt:string;initialImage?:string;previous?:BuildModel;onCreate:(creation:Creation)=>void};
type Completed={model:BuildModel;scene:GeneratedScene;review:VisualReview|null;brief:DesignBrief};
// Scale first: the reference sheet's real metres become a target in studs and plates, and the
// scale plan says how thick a hollow shell at that size can be within the piece budget. When
// even thin walls do not fit, the target itself is reduced so the checks and the designer agree.
function planSheet(sheet:ReferenceSheet,b:DesignBrief):ReferenceSheet{
 const target=targetExtents(sheet,b);if(!target)return {...sheet,target:undefined,plan:undefined};
 const plan=shellPlan(target,b.maxPieces,sheet.kind,sheet.openness??null);
 return {...sheet,target:plan.fits||!plan.recommend?target:{...target,...plan.recommend},plan};
}
export default function Generator({open,onOpenChange,initialPrompt,initialImage,previous,onCreate}:Props){
 const [reference,setReference]=useState<string|null>(null),[sheet,setSheet]=useState<ReferenceSheet|null>(null);
 const draftId=useRef("");
 // Every completed or kept draft is written to the browser's design library so backing out never loses it.
 const persist=(m:BuildModel,s:GeneratedScene,r:VisualReview|null,b:DesignBrief)=>{try{void saveDesign(packDesign({...m,name:previous?.name||m.name,generation:s,shopping:previous?.shopping,detail:b.size,libraryId:draftId.current,design:{brief:b,manual,locked,revisions:revisions.current,review:r||undefined,reviewStale:!r}},"draft"));}catch{/* drafts that cannot be serialized stay in this tab */}};
 const [budget,setBudget]=useState<BudgetSnapshot|null>(null);
 // The builder's notes: what it looked up, the scale it settled on, its own reasoning summaries as they stream, the architect's critique and the review.
 const [notes,setNotes]=useState<{phase:string;text:string;live?:boolean}[]>([]);
 const note=(phase:string,text:string)=>{const clean=text.trim();if(clean)setNotes(list=>[...list,{phase,text:clean}]);};
 const thought=(phase:string,delta:string)=>setNotes(list=>{const last=list[list.length-1];if(last&&last.live&&last.phase===phase)return [...list.slice(0,-1),{...last,text:(last.text+delta).slice(-6000)}];return [...list,{phase,text:delta.trimStart(),live:true}];});
 const notesEnd=useRef<HTMLDivElement>(null);
 useEffect(()=>{notesEnd.current?.scrollIntoView({block:"nearest"});},[notes]);
 const [interrupted,setInterrupted]=useState(false),[errorCode,setErrorCode]=useState("");
 const budgetBlocked=["BUDGET_LIMIT","BUDGET_ACCOUNTING","BUDGET_MODEL"].includes(errorCode);
 const partialDraft=useRef<Completed|null>(null);
 const [mobilePanel,setMobilePanel]=useState("preview"),[motionPaused,setMotionPaused]=useState(false),[replay,setReplay]=useState(0),[previewError,setPreviewError]=useState(""),[elapsed,setElapsed]=useState(0);
 const startedAt=useRef(0),previewQueue=useRef<PreviewQueue<GeneratedScene,BuildModel>|null>(null);
 const [brief,setBrief]=useState<DesignBrief>(defaultBrief()),[setup,setSetup]=useState(true),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[phase,setPhase]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState("");
 const [draft,setDraft]=useState<BuildModel|null>(null),[scene,setScene]=useState<GeneratedScene|null>(null),[review,setReview]=useState<VisualReview|null>(null),[shapeCount,setShapeCount]=useState(0),[configured,setConfigured]=useState<boolean|null>(null),[view,setView]=useState("perspective");
 const [apiKey,setApiKey]=useState(""),[showConnection,setShowConnection]=useState(false),[locked,setLocked]=useState<string[]>([]),[manual,setManual]=useState<ManualEdits>(emptyManual()),[messages,setMessages]=useState<{role:"you"|"builder";text:string}[]>([]);
 const controller=useRef<AbortController|null>(null),requestId=useRef(0),worker=useRef<Worker|null>(null),workerId=useRef(0),wasOpen=useRef(false),running=useRef(false);
 const pending=useRef(new Map<number,{resolve:(model:BuildModel)=>void;reject:(error:Error)=>void}>()),lastComplete=useRef<Completed|null>(null),revisions=useRef<NonNullable<BuildModel["design"]>["revisions"]>([]);
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),1000);return()=>clearInterval(timer);},[busy]);
 const checks=useMemo(()=>draft&&!busy?designChecks(draft,brief,sheet?.target):null,[draft,brief,busy,sheet]);
 const visualPassed=!!review&&review.recognizable&&review.features.every(f=>f.status==="visible")&&(!review.revision||["visible","not_requested"].includes(review.revision.status)),ready=checks?.pass&&visualPassed&&!interrupted;
 const components=useMemo(()=>[...new Set(scene?.shapes.map(s=>s.component||s.label)||[])],[scene]),diff=scene?sceneDiff(previous?.generation,scene):null;
 useEffect(()=>{
  worker.current=new Worker(new URL("./generation.worker.ts",import.meta.url),{type:"module"});
  worker.current.onmessage=e=>{const task=pending.current.get(e.data.id);if(task){pending.current.delete(e.data.id);if(e.data.error)task.reject(Error(e.data.error));else task.resolve(e.data.model);}};
  worker.current.onerror=()=>{worker.current?.terminate();worker.current=null;for(const task of pending.current.values())task.reject(Error("The brick assembler could not start. Reload and try again."));pending.current.clear();};
  return()=>{requestId.current++;controller.current?.abort();worker.current?.terminate();for(const task of pending.current.values())task.reject(Error("Generation closed."));pending.current.clear();};
 },[]);
 function compile(next:GeneratedScene,b:DesignBrief,base?:GeneratedScene,preview=false){return new Promise<BuildModel>((resolve,reject)=>{if(!worker.current){reject(Error("The brick assembler is unavailable. Reload and try again."));return;}const id=++workerId.current;pending.current.set(id,{resolve,reject});worker.current.postMessage({id,scene:next,manual,hollow:b.hollow,smooth:b.finish==="smooth",previous:preview&&!locked.length?undefined:base,locked});});}
 useEffect(()=>{if(open&&!wasOpen.current){const session=++requestId.current,old=previous?.design,b=old?.brief||defaultBrief(initialPrompt||previous?.description||"");setBrief(b);setPrompt("");setError("");setErrorCode("");setInterrupted(false);partialDraft.current=null;setPreviewError("");setMotionPaused(false);setReplay(0);setElapsed(0);const normalized=previous?.generation?normalizeScene(previous.generation):null;setScene(normalized);setDraft(previous||null);setReview(old?.reviewStale?null:old?.review||null);setLocked(old?.locked||[]);setManual(old?.manual||emptyManual());revisions.current=[...(old?.revisions||[])];setMessages(revisions.current.flatMap(r=>[{role:"you" as const,text:r.request},{role:"builder" as const,text:r.summary}]));draftId.current=previous?.libraryId||newDesignId();setReference(previous?null:initialImage||null);setSheet(null);setSetup(!previous);setShapeCount(0);setStatus("");setPhase("");setBusy(false);running.current=false;setShowConnection(false);setConfigured(null);lastComplete.current=previous?.generation?{model:previous,scene:normalized!,review:old?.reviewStale?null:old?.review||null,brief:b}:null;
   void fetch("/api/generate",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(requestId.current===session)setConfigured(Boolean(data.configured));}).catch(()=>{if(requestId.current===session){setConfigured(false);setError("Could not check the AI connection. Connect your key below to continue.");}});
  }wasOpen.current=open;
 },[open]);
 function restore(){const last=lastComplete.current;setDraft(last?.model||null);setScene(last?.scene||null);setReview(last?.review||null);if(last)setBrief(last.brief);}
 function stop(){previewQueue.current?.cancel();requestId.current++;controller.current?.abort();running.current=false;setBusy(false);setPhase("");if(partialDraft.current){const saved=partialDraft.current;setDraft(saved.model);setScene(saved.scene);setReview(null);setInterrupted(true);persist(saved.model,saved.scene,null,saved.brief);setStatus("Stopped. Your in-progress draft is kept in your designs.");}else{setStatus("Stopped. Your last completed draft is preserved.");restore();}}
 const headers=(key=apiKey)=>({"Content-Type":"application/json",...(key?{"x-brickwork-api-key":key}:{})});
 async function visual(model:BuildModel,b:DesignBrief,abort:AbortController,revision="",key=apiKey,signature:string[]=[]){
  setPhase("review");setStatus("Looking over the finished model…");const {renderReviewViews}=await import("@/lib/render-review");abort.signal.throwIfAborted();const images=renderReviewViews(model);abort.signal.throwIfAborted();
  // The designer's own signature features are reviewed alongside the brief's required ones.
  const features=[...b.features,...signature.filter(f=>!b.features.includes(f))].slice(0,12);
  const response=await fetch("/api/review",{method:"POST",signal:abort.signal,headers:headers(key),body:JSON.stringify({brief:{...b,features},images,revision})});
  if(!response.ok){const data=await response.json();throw new GenerationError(data.error||"Visual review could not start.",data.code||"REVIEW_FAILED");}
  if(!response.body)throw new GenerationError("Visual review lost its connection. Your design is kept.","CONNECTION_LOST");
  let result:VisualReview|undefined;for await(const event of readEvents(response.body)){if(event.type==="budget")setBudget(event.budget);if(event.type==="error")throw new GenerationError(event.message,event.code||"REVIEW_FAILED");if(event.type==="complete")result=event.review;}
  if(!result)throw new GenerationError("Visual review lost its connection. Your design is kept. Run the review again.","CONNECTION_LOST");return result;
 }
 async function blockout(model:BuildModel,b:DesignBrief,abort:AbortController,key:string,sheet:ReferenceSheet|null,signature:string[]):Promise<MassingCritique>{
  setPhase("massing-check");setStatus("Checking the blockout against the real thing…");const {renderReviewViews}=await import("@/lib/render-review");abort.signal.throwIfAborted();const images=renderReviewViews(model);abort.signal.throwIfAborted();
  const response=await fetch("/api/review",{method:"POST",signal:abort.signal,headers:headers(key),body:JSON.stringify({brief:b,images,stage:"massing",sheet:sheet||undefined,signature})});
  if(!response.ok){const data=await response.json();throw new GenerationError(data.error||"The blockout review could not start.",data.code||"REVIEW_FAILED");}
  if(!response.body)throw new GenerationError("The blockout review lost its connection.","CONNECTION_LOST");
  let result:MassingCritique|undefined;for await(const event of readEvents(response.body)){if(event.type==="budget")setBudget(event.budget);if(event.type==="error")throw new GenerationError(event.message,event.code||"REVIEW_FAILED");if(event.type==="complete")result=event.critique;}
  if(!result)throw new GenerationError("The blockout review lost its connection.","CONNECTION_LOST");return result;
 }
 async function run(reviewOnly=false,keyOverride?:string,fresh?:{brief:DesignBrief}){
  const activeKey=keyOverride||apiKey;if(running.current)return;if(!configured&&!activeKey){setShowConnection(true);setMobilePanel("refine");setError("");requestAnimationFrame(()=>document.getElementById("generation-key")?.focus());return;}
  const source=fresh?.brief||brief;
  const parsed=briefSchema.safeParse({...source,idea:source.idea.trim(),features:source.features.map(s=>s.trim()).filter(Boolean)});if(!parsed.success){setError("Check the brief: add an idea, keep each required detail under 160 characters, and use the displayed size and piece limits.");return;}
  const b=parsed.data;if(locked.length&&lastComplete.current&&b.hollow!==lastComplete.current.brief.hollow){setError("Unlock the protected components before changing hollow interiors.");return;}const text=scene&&!fresh?prompt.trim()||(interrupted?continuationPrompt(b.idea):"Repair the failed checks while preserving the original design."):b.idea,original=fresh?undefined:scene||undefined;
  const runId=++requestId.current,abort=new AbortController();controller.current=abort;previewQueue.current?.cancel();startedAt.current=Date.now();setElapsed(0);setPreviewError("");setErrorCode("");partialDraft.current=interrupted&&draft&&scene?{model:draft,scene,review:null,brief:b}:null;running.current=true;setBusy(true);setMobilePanel("preview");setSetup(false);setBrief(b);setError("");setReview(null);setShapeCount(0);setNotes([]);
  let best:Completed|null=null,bestScore=Infinity,feedback:string[]=[],candidate=original,research=sheet&&fresh?planSheet(sheet,b):sheet;
  if(fresh){setBrief(b);setScene(null);setDraft(null);setReview(null);setSheet(research);}
  const alive=()=>{abort.signal.throwIfAborted();if(requestId.current!==runId)throw new DOMException("Cancelled","AbortError");};
  try{
   if(reviewOnly&&draft&&scene){const r=await visual(draft,b,abort,prompt.trim(),activeKey,scene.signature||[]);alive();best={model:draft,scene,review:r,brief:b};}
   else{
    setMessages(m=>[...m,{role:"you",text}]);
    if(!original&&!research){
     // Real subjects get looked up first so the designer works from facts, not memory. A failed lookup is not fatal.
     setPhase("research");setStatus("Checking whether this is a real thing to look up…");
     try{const r=await fetch("/api/research",{method:"POST",signal:abort.signal,headers:headers(activeKey),body:JSON.stringify({idea:b.idea})});const data=await r.json();alive();if(data.budget)setBudget(data.budget);if(r.ok&&data.sheet?.searchable){research=planSheet(data.sheet,b);setSheet(research);setStatus(`Found the real ${data.sheet.subject}. Designing from its measurements…`);if(data.thinking)note("Looking it up",data.thinking);note("Found",`${data.sheet.subject}${data.searches?.length?` (searched: ${data.searches.join("; ")})`:""}. ${data.sheet.summary} ${[data.sheet.length_m&&`${data.sheet.length_m} m long`,data.sheet.width_m&&`${data.sheet.width_m} m wide`,data.sheet.height_m&&`${data.sheet.height_m} m tall`].filter(Boolean).join(", ")}. ${data.sheet.proportions}${data.sheet.distinctive?.length?` Must have: ${data.sheet.distinctive.join("; ")}.`:""}`);if(research.target)note("Scale",`${research.target.x} × ${research.target.z} studs, ${research.target.y} plates tall${research.plan?research.plan.fits?`; ${research.plan.walls?`hollow with ${research.plan.walls}-stud walls`:"solid masses fit"}, about ${research.plan.estimate.toLocaleString()} pieces for the main masses`:`; the full-size skin alone would take about ${research.plan.estimate.toLocaleString()} pieces, so this is the largest size the budget builds`:""}.`);}else if(r.ok&&data.sheet){note("Looking it up",`Not a specific real subject, so no lookup. Designing "${b.idea}" from the brief.`);}}catch(e){alive();}
    }
    if(!original){setPhase("foundation");setStatus("Laying the display foundation…");candidate=foundationScene(b);const foundation=await compile(candidate,b);alive();setDraft({...foundation,length:b.maxWidth,width:b.maxDepth,height:b.maxHeight});}
    if(original&&draft)feedback=[...designChecks(draft,b,research?.target).issues,...(review?.features.filter(f=>f.status!=="visible").map(f=>`${f.feature}: ${f.evidence}`)||[])];
    // One streamed design call. The canvas follows every pass live; a later pass starts from the previous pass's shapes (the base event).
    const stream=async(previousScene:GeneratedScene|undefined,extra:{stage?:"massing"|"detail";massingCritique?:string[];feedback?:string[];budget?:{limit:number;used:number;remaining:number;byComponent:{component:string;pieces:number}[]};label?:string})=>{
     let header:SceneHeader|null=null,shapes:Shape[]=[],result:GeneratedScene|undefined,geometryError="";setShapeCount(0);
     const previews=new PreviewQueue<GeneratedScene,BuildModel>(async snapshot=>{const m=await compile(snapshot,b,original,true);return {...m,generation:snapshot,length:snapshot.dimensions.x,width:snapshot.dimensions.z,height:snapshot.dimensions.y};},m=>{if(requestId.current===runId){setDraft(m);setPreviewError("");if(m.generation&&canKeepPartial(m.generation,m))partialDraft.current={model:m,scene:m.generation,review:null,brief:b};}},e=>{if(requestId.current===runId&&!(e instanceof Error&&/draft is empty/.test(e.message)))setPreviewError(e instanceof Error?e.message:"Live preview could not update.");},350);previewQueue.current=previews;const cancelPreview=()=>previews.cancel();abort.signal.addEventListener("abort",cancelPreview,{once:true});
     const response=await fetch("/api/generate",{method:"POST",signal:abort.signal,headers:headers(activeKey),body:JSON.stringify({prompt:text,detail:b.size,brief:b,reference:reference||undefined,research:research||undefined,previous:previousScene,locked,feedback:extra.feedback,stage:extra.stage,massingCritique:extra.massingCritique,budget:extra.budget,history:revisions.current.slice(-8).map(({request,summary})=>({request,summary}))})});
     if(!response.ok){const body=await response.json();throw new GenerationError(body.error||"Generation could not start.",body.code||"GENERATION_FAILED");}if(!response.body)throw Error("No generation stream was returned.");
     try{for await(const event of readEvents(response.body)){
      alive();if(event.type==="budget")setBudget(event.budget);else if(event.type==="thought")thought(extra.label||(extra.stage==="massing"?"Blocking out":extra.stage==="detail"?"Detailing":original?"Revising":"Designing"),event.text);else if(event.type==="header"){header=event.header;if(event.header.signature?.length)note("Signature",event.header.signature.join(" · "));}
      else if(event.type==="base"){shapes=event.shapes;setShapeCount(shapes.length);}
      else if(event.type==="shape"){const at=shapes.findIndex(s=>(s.id||s.label)===(event.shape.id||event.shape.label));if(at>=0)shapes[at]=event.shape;else shapes.push(event.shape);setShapeCount(shapes.length);setStatus(`${extra.stage==="massing"?"Blocking out":"Shaping"} ${event.shape.label.toLowerCase()}…`);
       if(header)previews.push({...header,shapes:[...shapes]});
      }else if(event.type==="complete")result=event.scene;else if(event.type==="error"){if(event.code==="INVALID_GEOMETRY"||/outside the build area|no volume|too complex|duplicate shape IDs|repeats too many|shape limit|incomplete design/.test(event.message))geometryError=event.message;else throw new GenerationError(event.message,event.code||"GENERATION_FAILED");}
     }}finally{await previews.flush();previews.cancel();abort.signal.removeEventListener("abort",cancelPreview);}
     alive();return {result,geometryError};
    };
    // Fresh designs work the way an architect does: block out the primary masses at final scale,
    // have the blockout checked against the real subject, then detail the corrected blockout.
    let massingScene:GeneratedScene|undefined,massingNotes:string[]|undefined,massingPieces=0;
    if(!original){
     setPhase("massing");setStatus("Blocking out the main masses…");note("Blockout","Placing the primary masses at final size before any detail.");
     const m=await stream(candidate,{stage:"massing"});
     if(m.result&&m.result.shapes.length>1){
      massingScene=m.result;candidate=m.result;
      try{const built=await compile(m.result,b);alive();setDraft(built);massingPieces=built.pieces.length;const critique=await blockout(built,b,abort,activeKey,research,m.result.signature||[]);alive();massingNotes=critique.corrections;if(critique.thinking)note("Architect",critique.thinking);note("Architect",`${critique.ready?"Approved.":"Corrections."} ${critique.summary}${critique.corrections.length?` ${critique.corrections.join(" ")}`:""}`);setMessages(list=>[...list,{role:"builder",text:`Blockout ${critique.ready?"approved":"reviewed"}: ${critique.summary}${critique.corrections.length?` Corrections: ${critique.corrections.join(" ")}`:""}`}]);}
      catch(e){alive();if(e instanceof GenerationError&&["BUDGET_LIMIT","BUDGET_ACCOUNTING","BUDGET_MODEL","AI_AUTH","AI_NOT_CONNECTED"].includes(e.code))throw e;massingNotes=[];}
     }
    }
    setPhase("design");setStatus(massingScene?"Detailing the blockout…":"Composing your design…");note(massingScene?"Detail":"Design",massingScene?"Applying the corrections, then detailing every component.":original?"Revising the existing scene.":"Composing the design in one pass.");
    // The detail pass gets the real count: what the blockout already costs and what is left for detail.
    const detailBudget=massingScene?{limit:b.maxPieces,used:massingPieces,remaining:b.maxPieces-massingPieces,byComponent:componentBudget(massingScene,massingPieces)}:undefined;
    if(detailBudget)note("Budget",`The blockout costs ${massingPieces.toLocaleString()} of ${b.maxPieces.toLocaleString()} pieces; ${Math.max(0,detailBudget.remaining).toLocaleString()} remain for detail.`);
    let {result,geometryError}=await stream(candidate,{stage:massingScene?"detail":undefined,massingCritique:massingNotes,feedback,budget:detailBudget});
    // One trim pass when the design lands well over budget: the designer gets the real per-component cost and cuts.
    if(result&&!geometryError){
     const over=await compile(result,b,original).catch(()=>null);alive();
     if(over&&over.pieces.length>b.maxPieces*1.1){
      const excess=over.pieces.length-b.maxPieces,by=componentBudget(result,over.pieces.length);
      setPhase("design");setStatus(`Over budget by ${excess.toLocaleString()} pieces. Trimming…`);note("Budget",`${over.pieces.length.toLocaleString()} pieces, ${excess.toLocaleString()} over the ${b.maxPieces.toLocaleString()} limit. ${by.slice(0,6).map(r=>`${r.component} ${r.pieces}`).join(", ")}. Trimming.`);
      // A trim that cannot run (budget, connection) never costs the design: the fuller result stands.
      const trimmed=await stream(result,{feedback:[`Over budget: ${over.pieces.length} pieces against a limit of ${b.maxPieces}. Cut at least ${excess} pieces. Remove or simplify the components that cost the most beyond their importance (buried mass, repeated texture, secondary accessories) and keep every signature feature; do not add anything.`],budget:{limit:b.maxPieces,used:over.pieces.length,remaining:b.maxPieces-over.pieces.length,byComponent:by},label:"Trimming"}).catch(e=>{alive();note("Budget",`Could not trim: ${e instanceof Error?e.message:"the trim pass failed"}. Keeping the fuller design.`);return {result:undefined,geometryError:""};});
      if(trimmed.result&&!trimmed.geometryError){const check=await compile(trimmed.result,b,original).catch(()=>null);alive();if(check&&check.pieces.length<over.pieces.length){result=trimmed.result;note("Budget",`Trimmed to ${check.pieces.length.toLocaleString()} pieces.`);}else note("Budget","The trim did not reduce the count; keeping the fuller design.");}
     }
    }
    if(geometryError){if(best)throw new GenerationError(geometryError,"INVALID_GEOMETRY");throw new GenerationError(geometryError,"INVALID_GEOMETRY");}if(!result)throw new GenerationError("The connection ended before your design was finished. Continue from the saved draft.","CONNECTION_LOST");
    try{
     setPhase("check");setStatus("Packing bricks and checking every connection…");note("Design",result.description);const m=await compile(result,b,original);alive();setDraft(m);setPreviewError("");partialDraft.current=null;const c=designChecks(m,b,research?.target);lastComplete.current={model:m,scene:result,review:null,brief:b};note("Checks",c.pass?`${m.pieces.length.toLocaleString()} pieces, every digital check passed.`:`${m.pieces.length.toLocaleString()} pieces. ${c.issues.join(" ")}`);
     let r:VisualReview|null=null,reviewError="";
     try{r=await visual(m,b,abort,original?prompt.trim():"",activeKey,result.signature||[]);alive();if(r.thinking)note("Judge",r.thinking);note("Judge",`${r.recognizable?"Recognizable.":"Not recognizable yet."} ${r.summary}${r.improvements.length?` Suggested: ${r.improvements.join(" ")}`:""}`);}catch(e){alive();reviewError=e instanceof Error?e.message:"Visual review failed.";setErrorCode(generationFailure(e).code);}
     const visualIssues=r?[...(!r.recognizable?["The subject is not visually recognizable. Improve silhouette and proportions."]:[]),...(r.revision&&!["visible","not_requested"].includes(r.revision.status)?[`Requested change: ${r.revision.status}. ${r.revision.evidence}`]:[]),...r.features.filter(f=>f.status!=="visible").map(f=>`${f.feature}: ${f.status}. ${f.evidence}`)]:[];
     const score=c.issues.length*1000+c.audit.ungrounded.length+c.audit.unsupported.length+visualIssues.length*100+(!r?500:0);
     if(score<bestScore){bestScore=score;best={model:m,scene:result,review:r,brief:b};lastComplete.current=best;}
     if(reviewError)setError(reviewError);
    }catch(e){alive();if(!best)throw e;}
   }
   alive();if(!best)throw Error("No complete draft passed geometry compilation. Adjust your brief and try again.");
   lastComplete.current=best;partialDraft.current=null;setInterrupted(false);setDraft(best.model);setScene(best.scene);setReview(best.review);setPrompt("");setPhase("done");persist(best.model,best.scene,best.review,b);const c=designChecks(best.model,b,research?.target),visualOK=best.review?.recognizable&&best.review.features.every(f=>f.status==="visible")&&(!best.review.revision||["visible","not_requested"].includes(best.review.revision.status));
   setStatus(c.pass&&visualOK?"Finished. Every digital check passed.":"Finished. A few checks still need attention.");requestAnimationFrame(()=>document.querySelector(".generation-status")?.scrollIntoView({block:"nearest",behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));const summary=best.review?.summary||best.scene.description;setMessages(m=>[...m,{role:"builder",text:summary}]);if(!reviewOnly)revisions.current=[...revisions.current,{request:text,summary,at:new Date().toISOString()}].slice(-50);
  }catch(e){if(requestId.current!==runId)return;const recovered=best||partialDraft.current||lastComplete.current;if(recovered){setDraft(recovered.model);setScene(recovered.scene);setReview(recovered.review);persist(recovered.model,recovered.scene,recovered.review,b);setInterrupted(!best&&recovered===partialDraft.current);setStatus(!best&&recovered===partialDraft.current?"In-progress draft kept in this tab. Continue to finish the design.":"Your completed draft is preserved.");if(best)lastComplete.current=best;}else{restore();setStatus("Your idea is kept. Reconnect and try again.");}const failure=generationFailure(e);setError(failure.message);setErrorCode(failure.code);}
  finally{if(requestId.current===runId){running.current=false;setBusy(false);controller.current=null;}}
 }
 function useBuild(shop=false){if(!draft||!scene||busy)return;const lastRequest=messages.filter(m=>m.role==="you").at(-1)?.text;if(lastRequest&&revisions.current.at(-1)?.request!==lastRequest)revisions.current=[...revisions.current,{request:lastRequest,summary:review?.summary||scene.description,at:new Date().toISOString()}].slice(-50);const model:BuildModel={...draft,name:previous?.name||draft.name,generation:scene,shopping:previous?.shopping,detail:brief.size,libraryId:draftId.current,design:{brief,manual,locked,revisions:revisions.current,review:review||undefined,reviewStale:!review}};requestId.current++;onCreate({model,detail:brief.size,color:draft.inventory.find(r=>r.color!=="gray")?.color||"white",accent:"white",shop});onOpenChange(false);requestAnimationFrame(()=>document.getElementById("build-table")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));}
 return <Dialog open={open} onOpenChange={v=>{if(!v)stop();onOpenChange(v);}}><DialogContent onOpenAutoFocus={e=>{e.preventDefault();document.querySelector<HTMLElement>(".generator-dialog [data-slot=dialog-title]")?.focus({preventScroll:true});}} className={`generator-dialog design-flow ${setup?"is-brief":"is-design"} mobile-${mobilePanel} ${busy?"is-building":""}`}><DialogHeader><DialogTitle tabIndex={-1}>{setup?"Let’s make it yours.":busy?draft?"Taking shape.":"Every build starts with an idea.":draft?draft.name:error?"Let’s get this working.":"Your canvas is ready."}</DialogTitle><DialogDescription>{setup?"Start with your idea. The finer details are optional.":busy?"Follow the real design as it arrives, piece by piece.":draft?"Turn it around. Make it yours.":"Your idea is safe. Start when you’re ready."}</DialogDescription></DialogHeader>

 {!setup&&<div className="creation-toolbar"><span>{busy?phase==="review"?"Reviewing the details":phase==="check"?"Checking the connections":phase==="massing"?"Blocking out the masses":phase==="massing-check"?"Checking the blockout":phase==="repair"?"Refining the design":draft?"Building live":"Composing your idea":draft&&phase==="done"?<><Check size={15}/>Finished · {draft.pieces.length.toLocaleString()} pieces</>:draft?`${draft.pieces.length.toLocaleString()} pieces`:"Ready when you are"}</span><div><button disabled={!draft} aria-pressed={motionPaused} onClick={()=>setMotionPaused(v=>!v)}>{motionPaused?<Play size={16}/>:<Pause size={16}/>}<span>{motionPaused?"Resume":"Pause motion"}</span></button><button disabled={!draft||busy} onClick={()=>{setMotionPaused(false);setReplay(v=>v+1);}}><RotateCcw size={16}/><span>Replay</span></button><button aria-expanded={mobilePanel==="refine"} onClick={()=>{const show=mobilePanel!=="refine";setMobilePanel(show?"refine":"preview");if(show)requestAnimationFrame(()=>document.getElementById("creation-controls")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"}));}}><SlidersHorizontal size={16}/><span>{mobilePanel==="refine"?"Hide controls":"Refine"}</span></button></div></div>}<div className="generator-layout"><div id="creation-controls" className="generator-conversation">
 {setup?<>{reference&&<div className="brief-reference"><img src={reference} alt="Reference photo for this design"/><div><strong>Designing from your photo</strong><p>The builder studies this picture and sculpts what it shows. Add anything it should keep or change below.</p><button type="button" onClick={()=>setReference(null)}>Remove photo</button></div></div>}<BriefForm brief={brief} onChange={b=>{setBrief(b);setReview(null);}}/></>:<><div className="brief-recap"><strong>{brief.idea}</strong><span>{brief.detail} detail · up to {brief.maxPieces.toLocaleString()} pieces{brief.quality==="best"?" · Best (GPT-6 Astra)":brief.quality==="better"?" · Better (GPT-5.6 Sol)":""}</span><button disabled={busy} onClick={()=>setSetup(true)}>Edit brief</button></div>
 {sheet&&<div className="reference-sheet"><strong>Built from facts about {sheet.subject}</strong>{(sheet.length_m||sheet.width_m||sheet.height_m)&&<p>{[sheet.length_m&&`${sheet.length_m} m long`,sheet.width_m&&`${sheet.width_m} m wide`,sheet.height_m&&`${sheet.height_m} m tall`].filter(Boolean).join(" · ")}</p>}{sheet.target&&<p>Target at this size: {sheet.target.x} studs long · {sheet.target.z} studs deep · {sheet.target.y} plates tall{sheet.target.vertical>1?` · heights ×${sheet.target.vertical} so the ${sheet.kind==="bridge"?"towers":"structures"} read`:""}</p>}{sheet.plan&&<p>Scale plan: {sheet.plan.fits?sheet.plan.walls===0?`solid masses fit the budget, about ${sheet.plan.estimate.toLocaleString()} pieces`:`hollow with ${sheet.plan.walls}-stud walls, about ${sheet.plan.estimate.toLocaleString()} pieces for the shell`:`the full-size skin alone would take about ${sheet.plan.estimate.toLocaleString()} pieces, so the target is the largest size the ${brief.maxPieces.toLocaleString()}-piece budget can build`}</p>}{sheet.proportions&&<p>{sheet.proportions}</p>}{sheet.colors.length>0&&<p>Colors: {sheet.colors.join(", ")}</p>}{sheet.distinctive.length>0&&<ul>{sheet.distinctive.slice(0,5).map((d,i)=><li key={i}>{d}</li>)}</ul>}{sheet.sources.length>0&&<small>{sheet.sources.map((u,i)=><a key={i} href={u} target="_blank" rel="noreferrer">{new URL(u).hostname}</a>)}</small>}</div>}
 {scene&&!busy&&scene.signature&&scene.signature.length>0&&<div className="reference-sheet signature-sheet"><strong>Signature features</strong><p>{scene.signature.join(" · ")}</p></div>}
 {scene&&!busy&&<details className="component-locks"><summary><LockKeyhole size={15}/>{locked.length?`${locked.length} components protected`:"Protect parts you already love"}</summary><p>Locked components keep their geometry and color. Revisions that overlap them are rejected.</p><div>{components.map(c=><label key={c}><Checkbox checked={locked.includes(c)} onCheckedChange={v=>setLocked(list=>v?[...list,c]:list.filter(x=>x!==c))}/>{c}</label>)}</div>{(manual.bricks.length>0||manual.erase.length>0)&&<p>{manual.bricks.length} edited bricks and {manual.erase.length} erased regions are also protected.</p>}</details>}
 {notes.length>0&&<details className="builder-notes" open><summary>What the builder is thinking</summary><div className="builder-notes-list">{notes.map((n,i)=><div key={i} className={`builder-note ${n.live?"is-live":""}`}><span>{n.phase}</span><p>{n.text}</p></div>)}<div ref={notesEnd}/></div></details>}
 <details className="design-history"><summary>Design history</summary><div className="generation-messages">{messages.slice(-6).map((m,i)=><div className={`generation-message message-${m.role}`} key={i}><span>{m.role==="you"?"YOU":"BRICKWORK"}</span><p>{m.text}</p></div>)}</div></details>
 </>}
 <AIConnection configured={configured} apiKey={apiKey} busy={busy} active={open} expanded={showConnection} onExpand={setShowConnection} setup={setup} budget={budget} onBudget={setBudget} onConnect={key=>{setApiKey(key);setShowConnection(false);setError("");setErrorCode("");if(setup)void run(false,key);}} onForget={()=>{setApiKey("");setBudget(null);}}/>
 {busy&&<button className="button secondary" onClick={stop}><Square size={14}/>Stop and keep last draft</button>}
 {error&&<div className="creation-error" role="alert"><p>{error}</p>{!busy&&!budgetBlocked&&<button className="button secondary" onClick={()=>void run()}><RotateCcw size={14}/>Try again</button>}</div>}
 </div><div className="generation-preview"><div className="generation-preview-header"><span>{setup?"YOUR DESIGN BRIEF":busy?phase==="massing"||phase==="massing-check"?"BLOCKOUT":phase==="repair"?"REFINING":"LIVE DESIGN":draft?.name||"YOUR 3D BUILD"}</span>{busy&&<span><LoaderCircle size={13} className="spin"/>{shapeCount} shape definitions</span>}</div>
 {!setup&&<><div className="generation-canvas">{draft?<Viewport arrivals={{epoch:replay,paused:motionPaused}} pieces={draft.pieces} length={draft.length} width={draft.width} height={draft.height} modelKey="live-creation" explode={0} stage={100000} selected={null} view={view} reset={0} rotate={false} onPick={()=>{}}/>:<div className="generation-empty"><span className="empty-stage-label">{busy?"THE FIRST PIECES ARE ON THEIR WAY":error?"GENERATION PAUSED":"YOUR NEXT CREATION"}</span><strong>{busy?brief.idea:error?"Your idea is still here.":"An open canvas."}</strong><p>{busy?"Waiting for the builder’s first geometry. Bricks will appear here as soon as it arrives.":error?error:"Start a design from your brief."}</p>{!busy&&<button className="button primary" onClick={()=>setSetup(true)}>Back to my brief<ArrowRight size={16}/></button>}</div>}</div><button className="generation-assembly" disabled={!draft||busy} onClick={()=>{setMotionPaused(false);setReplay(v=>v+1);}}><Play size={17} fill="currentColor"/>Replay assembly</button><div className="review-camera">{["perspective","front","top"].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v}</button>)}</div></>}
 {previewError&&<p className="live-preview-error" role="status">Preview update: {previewError} The last visible draft is kept.</p>}{error&&<div className="stage-recovery" role="alert"><div><strong>{interrupted?"Your progress is kept.":draft&&scene?"Your design is kept.":"Let’s get your build going."}</strong><p>{error}</p></div>{!busy&&!budgetBlocked&&<button className="button secondary" onClick={()=>{if(errorCode==="AI_AUTH"||errorCode==="AI_NOT_CONNECTED"){setShowConnection(true);setMobilePanel("refine");requestAnimationFrame(()=>document.getElementById("creation-controls")?.scrollIntoView({block:"start",behavior:"auto"}));}else void run(Boolean(scene&&!interrupted&&(phase==="done"||phase==="review")));}}>{errorCode==="AI_AUTH"||errorCode==="AI_NOT_CONNECTED"?"AI settings":interrupted?"Continue design":scene&&(phase==="done"||phase==="review")?"Retry review":"Try again"}</button>}</div>}{busy&&<button className="mobile-stop button secondary" onClick={stop}><Square size={14}/>Stop and keep draft</button>}<div className={`generation-status ${draft&&!busy&&scene&&!setup?"is-finished":""}`} role="status">{busy?<LoaderCircle size={15} className="spin"/>:ready?<Check size={15}/>:<Sparkles size={15}/>}<p>{status||"Your brief is ready when you are."}</p>{budget&&<span className="live-budget">${budget.remaining.toFixed(2)} available · $10 limit</span>}{busy&&<span className="live-elapsed">{elapsed}s · {(draft?.pieces.length||0).toLocaleString()} bricks</span>}</div>
 {draft&&!busy&&scene&&!setup&&<form className="finish-feedback" onSubmit={e=>{e.preventDefault();void run();}}><label htmlFor="generation-prompt">{ready?"Want anything changed? Say it in your own words.":"What's wrong? Tell the builder in your own words."}</label><Textarea id="generation-prompt" rows={2} maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={ready?"Make the roof steeper and add a chimney on the left.":"The car is wider than it is long and the wheels are missing. Leave this blank to fix only the flagged checks."}/><div className="review-actions finish-actions"><button type="submit" className="button secondary" disabled={budgetBlocked||(ready&&prompt.trim().length<3)}><Send size={14}/>{interrupted?"Continue design":prompt.trim().length>=3?"Revise design":ready?"Describe a change to revise":"Repair flagged checks"}</button><button type="button" className="button secondary" disabled={interrupted||budgetBlocked} onClick={()=>void run(true)}><Eye size={14}/>Review again</button>{brief.size!=="large"&&<button type="button" className="button secondary" disabled={budgetBlocked} title="Start over at the largest size, 4,000 pieces in 80 × 80 studs" onClick={()=>void run(false,undefined,{brief:{...brief,size:"large",maxWidth:80,maxDepth:80,maxHeight:160,maxPieces:4000}})}><Maximize2 size={14}/>Rebuild bigger</button>}<button type="button" className="button secondary" onClick={()=>useBuild(true)} title="Open the shopping list for this design"><ShoppingBag size={14}/>Get the bricks</button><button type="button" className="button primary" onClick={()=>useBuild()}>{ready?"Open in studio":"Keep as working draft"}<ArrowRight size={16}/></button></div></form>}
 {draft&&!busy&&scene&&!setup&&<div className="generation-result">{interrupted&&<p className="unfinished-draft">Unfinished draft. Continue building before reviewing the complete design.</p>}<div><strong>{draft.pieces.length.toLocaleString()} pieces</strong><span>{(draft.length*.8).toFixed(1)} × {(draft.width*.8).toFixed(1)} × {(draft.height*.32).toFixed(1)} cm</span></div><details className="design-inspection"><summary>{ready?"Design checks passed":"Review design checks"}<span>{checks?.issues.length||0} geometry issues</span></summary><div className={`review-verdict ${ready?"passed":"needs-work"}`}><strong>{ready?"Digital checks passed":"Needs review"}</strong><span>{checks?.pass?"Support paths and size limits pass.":`${checks?.issues.length} geometry or brief checks need attention.`} {visualPassed?"Visual brief review passes.":"Visual brief review is incomplete or has concerns."}</span></div>
 {checks&&checks.issues.length>0&&<ul className="review-issues">{checks.issues.map(i=><li key={i}>{i}</li>)}</ul>}{review&&<div className="feature-review"><p>{review.summary}</p>{review.revision&&review.revision.status!=="not_requested"&&<div><span className={`feature-state ${review.revision.status}`}>{review.revision.status}</span><strong>Your requested change</strong><p>{review.revision.evidence}</p></div>}{review.features.map((f,i)=><div key={i}><span className={`feature-state ${f.status}`}>{f.status}</span><strong>{f.feature}</strong><p>{f.evidence}</p></div>)}</div>}{diff&&previous&&<p className="diff-summary">{diff.added} shapes added · {diff.changed} changed · {diff.removed} removed</p>}<p className="review-limit">Digital checks cover geometry, support paths and visible details. Physical strength, fit and hand access still need a test build.</p>
 </details></div>}
 </div></div>{setup&&<div className="brief-commit"><span>Up to {brief.maxPieces.toLocaleString()} pieces<small>{brief.detail==="signature"?"Signature":brief.detail==="balanced"?"Essential":"Detailed"} design</small></span><button className="button primary begin-design" disabled={brief.idea.trim().length<3||busy||configured===null&&!apiKey} onClick={()=>void run()}><Sparkles size={17}/>{configured===null&&!apiKey?"Checking connection…":configured||apiKey?scene?"Rebuild design":"Build my design":"Connect to build"}<ArrowRight size={17}/></button></div>}</DialogContent></Dialog>;
}
