"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowRight,Check,LoaderCircle,RotateCcw,Send,Square,Sparkles,LockKeyhole,Eye,Play,Pause,SlidersHorizontal} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import AIConnection from "./ai-connection";
import type {BudgetSnapshot} from "@/lib/ai-budget";
import {Textarea} from "@/components/ui/textarea";
import {Switch} from "@/components/ui/switch";
import {Checkbox} from "@/components/ui/checkbox";
import Viewport from "./viewport";
import AssemblyPlayer from "./assembly-player";
import {saveDesign,packDesign,newDesignId} from "@/lib/design-library";
import BriefForm from "./design-brief";
import {normalizeScene} from "@/lib/generated-scene";
import {PreviewQueue,foundationScene} from "@/lib/live-arrivals";
import {readEvents} from "@/lib/generation-stream";
import {canKeepPartial,continuationPrompt} from "@/lib/generation-recovery";
import {GenerationError,generationFailure} from "@/lib/generation-errors";
import {briefSchema,defaultBrief,emptyManual,designChecks,sceneDiff} from "@/lib/design-project";
import type {DesignBrief,VisualReview,ManualEdits} from "@/lib/design-project";
import type {GeneratedScene,SceneHeader,Shape} from "@/lib/generated-scene";
import type {BuildModel} from "@/lib/models";
import type {Creation} from "./create-build";
type Props={open:boolean;onOpenChange:(open:boolean)=>void;initialPrompt:string;previous?:BuildModel;onCreate:(creation:Creation)=>void};
type Completed={model:BuildModel;scene:GeneratedScene;review:VisualReview|null;brief:DesignBrief};
export default function Generator({open,onOpenChange,initialPrompt,previous,onCreate}:Props){
 const [assemblyPreview,setAssemblyPreview]=useState(false);
 const draftId=useRef("");
 // Every completed or kept draft is written to the browser's design library so backing out never loses it.
 const persist=(m:BuildModel,s:GeneratedScene,r:VisualReview|null,b:DesignBrief)=>{try{void saveDesign(packDesign({...m,name:previous?.name||m.name,generation:s,shopping:previous?.shopping,detail:b.size,libraryId:draftId.current,design:{brief:b,manual,locked,revisions:revisions.current,review:r||undefined,reviewStale:!r}},"draft"));}catch{/* drafts that cannot be serialized stay in this tab */}};
 const [budget,setBudget]=useState<BudgetSnapshot|null>(null);
 const [interrupted,setInterrupted]=useState(false),[errorCode,setErrorCode]=useState("");
 const budgetBlocked=["BUDGET_LIMIT","BUDGET_ACCOUNTING","BUDGET_MODEL"].includes(errorCode);
 const partialDraft=useRef<Completed|null>(null);
 const [mobilePanel,setMobilePanel]=useState("preview"),[motionPaused,setMotionPaused]=useState(false),[replay,setReplay]=useState(0),[previewError,setPreviewError]=useState(""),[elapsed,setElapsed]=useState(0);
 const startedAt=useRef(0),previewQueue=useRef<PreviewQueue<GeneratedScene,BuildModel>|null>(null);
 const [brief,setBrief]=useState<DesignBrief>(defaultBrief()),[setup,setSetup]=useState(true),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[phase,setPhase]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState("");
 const [draft,setDraft]=useState<BuildModel|null>(null),[scene,setScene]=useState<GeneratedScene|null>(null),[review,setReview]=useState<VisualReview|null>(null),[shapeCount,setShapeCount]=useState(0),[configured,setConfigured]=useState<boolean|null>(null),[view,setView]=useState("perspective");
 const [apiKey,setApiKey]=useState(""),[showConnection,setShowConnection]=useState(false),[autoRepair,setAutoRepair]=useState(true),[locked,setLocked]=useState<string[]>([]),[manual,setManual]=useState<ManualEdits>(emptyManual()),[messages,setMessages]=useState<{role:"you"|"builder";text:string}[]>([]);
 const controller=useRef<AbortController|null>(null),requestId=useRef(0),worker=useRef<Worker|null>(null),workerId=useRef(0),wasOpen=useRef(false),running=useRef(false);
 const pending=useRef(new Map<number,{resolve:(model:BuildModel)=>void;reject:(error:Error)=>void}>()),lastComplete=useRef<Completed|null>(null),revisions=useRef<NonNullable<BuildModel["design"]>["revisions"]>([]);
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),1000);return()=>clearInterval(timer);},[busy]);
 const checks=useMemo(()=>draft&&!busy?designChecks(draft,brief):null,[draft,brief,busy]);
 const visualPassed=!!review&&review.recognizable&&review.features.every(f=>f.status==="visible")&&(!review.revision||["visible","not_requested"].includes(review.revision.status)),ready=checks?.pass&&visualPassed&&!interrupted;
 const components=useMemo(()=>[...new Set(scene?.shapes.map(s=>s.component||s.label)||[])],[scene]),diff=scene?sceneDiff(previous?.generation,scene):null;
 useEffect(()=>{
  worker.current=new Worker(new URL("./generation.worker.ts",import.meta.url),{type:"module"});
  worker.current.onmessage=e=>{const task=pending.current.get(e.data.id);if(task){pending.current.delete(e.data.id);if(e.data.error)task.reject(Error(e.data.error));else task.resolve(e.data.model);}};
  worker.current.onerror=()=>{worker.current?.terminate();worker.current=null;for(const task of pending.current.values())task.reject(Error("The brick assembler could not start. Reload and try again."));pending.current.clear();};
  return()=>{requestId.current++;controller.current?.abort();worker.current?.terminate();for(const task of pending.current.values())task.reject(Error("Generation closed."));pending.current.clear();};
 },[]);
 function compile(next:GeneratedScene,b:DesignBrief,base?:GeneratedScene,preview=false){return new Promise<BuildModel>((resolve,reject)=>{if(!worker.current){reject(Error("The brick assembler is unavailable. Reload and try again."));return;}const id=++workerId.current;pending.current.set(id,{resolve,reject});worker.current.postMessage({id,scene:next,manual,hollow:b.hollow,previous:preview&&!locked.length?undefined:base,locked});});}
 useEffect(()=>{if(open&&!wasOpen.current){const session=++requestId.current,old=previous?.design,b=old?.brief||defaultBrief(initialPrompt||previous?.description||"");setBrief(b);setPrompt("");setError("");setErrorCode("");setInterrupted(false);partialDraft.current=null;setPreviewError("");setMotionPaused(false);setReplay(0);setElapsed(0);const normalized=previous?.generation?normalizeScene(previous.generation):null;setScene(normalized);setDraft(previous||null);setReview(old?.reviewStale?null:old?.review||null);setLocked(old?.locked||[]);setManual(old?.manual||emptyManual());revisions.current=[...(old?.revisions||[])];setMessages(revisions.current.flatMap(r=>[{role:"you" as const,text:r.request},{role:"builder" as const,text:r.summary}]));draftId.current=previous?.libraryId||newDesignId();setSetup(!previous);setAssemblyPreview(false);setShapeCount(0);setStatus("");setPhase("");setBusy(false);running.current=false;setShowConnection(false);setConfigured(null);lastComplete.current=previous?.generation?{model:previous,scene:normalized!,review:old?.reviewStale?null:old?.review||null,brief:b}:null;
   void fetch("/api/generate",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(requestId.current===session)setConfigured(Boolean(data.configured));}).catch(()=>{if(requestId.current===session){setConfigured(false);setError("Could not check the AI connection. Connect your key below to continue.");}});
  }wasOpen.current=open;
 },[open]);
 function restore(){const last=lastComplete.current;setDraft(last?.model||null);setScene(last?.scene||null);setReview(last?.review||null);if(last)setBrief(last.brief);}
 function stop(){previewQueue.current?.cancel();requestId.current++;controller.current?.abort();running.current=false;setBusy(false);setPhase("");if(partialDraft.current){const saved=partialDraft.current;setDraft(saved.model);setScene(saved.scene);setReview(null);setInterrupted(true);persist(saved.model,saved.scene,null,saved.brief);setStatus("Stopped. Your in-progress draft is kept in your designs.");}else{setStatus("Stopped. Your last completed draft is preserved.");restore();}}
 const headers=(key=apiKey)=>({"Content-Type":"application/json",...(key?{"x-brickwork-api-key":key}:{})});
 async function visual(model:BuildModel,b:DesignBrief,abort:AbortController,revision="",key=apiKey){
  setPhase("review");setStatus("Looking over the finished model…");const {renderReviewViews}=await import("@/lib/render-review");abort.signal.throwIfAborted();const images=renderReviewViews(model);abort.signal.throwIfAborted();
  const response=await fetch("/api/review",{method:"POST",signal:abort.signal,headers:headers(key),body:JSON.stringify({brief:b,images,revision})});
  if(!response.ok){const data=await response.json();throw new GenerationError(data.error||"Visual review could not start.",data.code||"REVIEW_FAILED");}
  if(!response.body)throw new GenerationError("Visual review lost its connection. Your design is kept.","CONNECTION_LOST");
  let result:VisualReview|undefined;for await(const event of readEvents(response.body)){if(event.type==="budget")setBudget(event.budget);if(event.type==="error")throw new GenerationError(event.message,event.code||"REVIEW_FAILED");if(event.type==="complete")result=event.review;}
  if(!result)throw new GenerationError("Visual review lost its connection. Your design is kept. Run the review again.","CONNECTION_LOST");return result;
 }
 async function run(reviewOnly=false,keyOverride?:string){
  const activeKey=keyOverride||apiKey;if(running.current)return;if(!configured&&!activeKey){setShowConnection(true);setMobilePanel("refine");setError("");requestAnimationFrame(()=>document.getElementById("generation-key")?.focus());return;}
  const parsed=briefSchema.safeParse({...brief,idea:brief.idea.trim(),features:brief.features.map(s=>s.trim()).filter(Boolean)});if(!parsed.success){setError("Check the brief: add an idea, keep each required detail under 160 characters, and use the displayed size and piece limits.");return;}
  const b=parsed.data;if(locked.length&&lastComplete.current&&b.hollow!==lastComplete.current.brief.hollow){setError("Unlock the protected components before changing hollow interiors.");return;}const text=scene?prompt.trim()||(interrupted?continuationPrompt(b.idea):"Repair the failed checks while preserving the original design."):b.idea,original=scene||undefined;
  const runId=++requestId.current,abort=new AbortController();controller.current=abort;previewQueue.current?.cancel();startedAt.current=Date.now();setElapsed(0);setPreviewError("");setErrorCode("");partialDraft.current=interrupted&&draft&&scene?{model:draft,scene,review:null,brief:b}:null;running.current=true;setBusy(true);setAssemblyPreview(false);setMobilePanel("preview");setSetup(false);setBrief(b);setError("");setReview(null);setShapeCount(0);
  let best:Completed|null=null,bestScore=Infinity,feedback:string[]=[],candidate=original;
  const alive=()=>{abort.signal.throwIfAborted();if(requestId.current!==runId)throw new DOMException("Cancelled","AbortError");};
  try{
   if(reviewOnly&&draft&&scene){const r=await visual(draft,b,abort,prompt.trim(),activeKey);alive();best={model:draft,scene,review:r,brief:b};}
   else{
    setMessages(m=>[...m,{role:"you",text}]);
    if(!original){setPhase("foundation");setStatus("Laying the display foundation…");candidate=foundationScene(b);const foundation=await compile(candidate,b);alive();setDraft({...foundation,length:b.maxWidth,width:b.maxDepth,height:b.maxHeight});}
    if(original&&draft)feedback=[...designChecks(draft,b).issues,...(review?.features.filter(f=>f.status!=="visible").map(f=>`${f.feature}: ${f.evidence}`)||[])];
    for(let attempt=0;attempt<=(autoRepair?2:0);attempt++){
     // Only the first pass streams into the canvas. Refinement keeps the finished draft on screen and swaps in the improved result once it compiles, instead of rebuilding from the foundation in view.
     const live=attempt===0;
     alive();setPhase(attempt?"repair":"design");setStatus(attempt?"Refining the details…":"Composing your design…");setShapeCount(0);
     let header:SceneHeader|null=null,shapes:Shape[]=[],result:GeneratedScene|undefined,geometryError="";
     const previews=new PreviewQueue<GeneratedScene,BuildModel>(async snapshot=>{const m=await compile(snapshot,b,original,true);return {...m,generation:snapshot,length:snapshot.dimensions.x,width:snapshot.dimensions.z,height:snapshot.dimensions.y};},m=>{if(requestId.current===runId){setDraft(m);setPreviewError("");if(m.generation&&canKeepPartial(m.generation,m))partialDraft.current={model:m,scene:m.generation,review:null,brief:b};}},e=>{if(requestId.current===runId&&!(e instanceof Error&&/draft is empty/.test(e.message)))setPreviewError(e instanceof Error?e.message:"Live preview could not update.");},350);previewQueue.current=previews;const cancelPreview=()=>previews.cancel();abort.signal.addEventListener("abort",cancelPreview,{once:true});
     const response=await fetch("/api/generate",{method:"POST",signal:abort.signal,headers:headers(activeKey),body:JSON.stringify({prompt:text,detail:b.size,brief:b,previous:candidate,locked,feedback,history:revisions.current.slice(-8).map(({request,summary})=>({request,summary}))})});
     if(!response.ok){const body=await response.json();throw new GenerationError(body.error||"Generation could not start.",body.code||"GENERATION_FAILED");}if(!response.body)throw Error("No generation stream was returned.");
     try{for await(const event of readEvents(response.body)){
      alive();if(event.type==="budget")setBudget(event.budget);else if(event.type==="header")header=event.header;
      else if(event.type==="shape"){shapes.push(event.shape);setShapeCount(shapes.length);if(live)setStatus(`Shaping ${event.shape.label.toLowerCase()}…`);
       if(header&&live)previews.push({...header,shapes:[...shapes]});
      }else if(event.type==="complete")result=event.scene;else if(event.type==="error"){if(event.code==="INVALID_GEOMETRY"||/outside the build area|no volume|too complex|duplicate shape IDs|repeats too many|shape limit|incomplete design/.test(event.message))geometryError=event.message;else throw new GenerationError(event.message,event.code||"GENERATION_FAILED");}
     }}finally{await previews.flush();previews.cancel();abort.signal.removeEventListener("abort",cancelPreview);}
     // A refinement that returns bad geometry never replaces a completed draft: retry while passes remain, otherwise finish with the best one.
     alive();if(geometryError){if(attempt<(autoRepair?2:0)){feedback=[geometryError];candidate=original;continue;}if(best)break;throw Error(geometryError);}if(!result)throw new GenerationError("The connection ended before your design was finished. Continue from the saved draft.","CONNECTION_LOST");
     try{
      setPhase("check");setStatus("Packing bricks and checking every connection…");const m=await compile(result,b,original);alive();setDraft(m);setPreviewError("");partialDraft.current=null;const c=designChecks(m,b);const structuralScore=c.issues.length*1000+c.audit.ungrounded.length+c.audit.unsupported.length;if(!best||structuralScore<bestScore){lastComplete.current={model:m,scene:result,review:null,brief:b};}
      let r:VisualReview|null=null,reviewError="";
      try{r=await visual(m,b,abort,original?prompt.trim():"",activeKey);alive();}catch(e){alive();reviewError=e instanceof Error?e.message:"Visual review failed.";setErrorCode(generationFailure(e).code);}
      const visualIssues=r?[...(!r.recognizable?["The subject is not visually recognizable. Improve silhouette and proportions."]:[]),...(r.revision&&!["visible","not_requested"].includes(r.revision.status)?[`Requested change: ${r.revision.status}. ${r.revision.evidence}`]:[]),...r.features.filter(f=>f.status!=="visible").map(f=>`${f.feature}: ${f.status}. ${f.evidence}`)]:[];
      const score=c.issues.length*1000+c.audit.ungrounded.length+c.audit.unsupported.length+visualIssues.length*100+(!r?500:0);
      if(score<bestScore){bestScore=score;best={model:m,scene:result,review:r,brief:b};lastComplete.current=best;}
      feedback=[...c.issues,...c.locations,...visualIssues,...(r?.improvements||[])].slice(0,40);candidate=result;
      if(reviewError){setError(reviewError);break;}if(c.pass&&!visualIssues.length)break;
     }catch(e){alive();feedback=[e instanceof Error?e.message:"Compilation failed. Repair the geometry."];if(attempt===(autoRepair?2:0)){if(best)break;throw e;}candidate=original;}
    }
   }
   alive();if(!best)throw Error("No complete draft passed geometry compilation. Adjust your brief and try again.");
   lastComplete.current=best;partialDraft.current=null;setInterrupted(false);setDraft(best.model);setScene(best.scene);setReview(best.review);setPrompt("");setPhase("done");persist(best.model,best.scene,best.review,b);const c=designChecks(best.model,b),visualOK=best.review?.recognizable&&best.review.features.every(f=>f.status==="visible")&&(!best.review.revision||["visible","not_requested"].includes(best.review.revision.status));
   setStatus(c.pass&&visualOK?"Finished. Every digital check passed.":"Finished. A few checks still need attention.");requestAnimationFrame(()=>document.querySelector(".generation-status")?.scrollIntoView({block:"nearest",behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));const summary=best.review?.summary||best.scene.description;setMessages(m=>[...m,{role:"builder",text:summary}]);if(!reviewOnly)revisions.current=[...revisions.current,{request:text,summary,at:new Date().toISOString()}].slice(-50);
  }catch(e){if(requestId.current!==runId)return;const recovered=best||partialDraft.current||lastComplete.current;if(recovered){setDraft(recovered.model);setScene(recovered.scene);setReview(recovered.review);persist(recovered.model,recovered.scene,recovered.review,b);setInterrupted(!best&&recovered===partialDraft.current);setStatus(!best&&recovered===partialDraft.current?"In-progress draft kept in this tab. Continue to finish the design.":"Your completed draft is preserved.");if(best)lastComplete.current=best;}else{restore();setStatus("Your idea is kept. Reconnect and try again.");}const failure=generationFailure(e);setError(failure.message);setErrorCode(failure.code);}
  finally{if(requestId.current===runId){running.current=false;setBusy(false);controller.current=null;}}
 }
 function useBuild(){if(!draft||!scene||busy)return;const lastRequest=messages.filter(m=>m.role==="you").at(-1)?.text;if(lastRequest&&revisions.current.at(-1)?.request!==lastRequest)revisions.current=[...revisions.current,{request:lastRequest,summary:review?.summary||scene.description,at:new Date().toISOString()}].slice(-50);const model:BuildModel={...draft,name:previous?.name||draft.name,generation:scene,shopping:previous?.shopping,detail:brief.size,libraryId:draftId.current,design:{brief,manual,locked,revisions:revisions.current,review:review||undefined,reviewStale:!review}};requestId.current++;onCreate({model,detail:brief.size,color:draft.inventory.find(r=>r.color!=="gray")?.color||"white",accent:"white"});onOpenChange(false);requestAnimationFrame(()=>document.getElementById("build-table")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}));}
 return <Dialog open={open} onOpenChange={v=>{if(!v)stop();onOpenChange(v);}}><DialogContent onOpenAutoFocus={e=>{e.preventDefault();document.querySelector<HTMLElement>(".generator-dialog [data-slot=dialog-title]")?.focus({preventScroll:true});}} className={`generator-dialog design-flow ${setup?"is-brief":"is-design"} mobile-${mobilePanel} ${busy?"is-building":""}`}><DialogHeader><p className="eyebrow">BRICKWORK / YOUR NEXT BUILD</p><DialogTitle tabIndex={-1}>{setup?"Let’s make it yours.":busy?draft?"Taking shape.":"Every build starts with an idea.":draft?draft.name:error?"Let’s get this working.":"Your canvas is ready."}</DialogTitle><DialogDescription>{setup?"Start with your idea. The finer details are optional.":busy?"Follow the real design as it arrives, piece by piece.":draft?"Turn it around. Make it yours.":"Your idea is safe. Start when you’re ready."}</DialogDescription></DialogHeader>

 {!setup&&<div className="creation-toolbar"><span>{busy?phase==="review"?"Reviewing the details":phase==="check"?"Checking the connections":phase==="repair"?"Refining the design":draft?"Building live":"Composing your idea":draft&&phase==="done"?<><Check size={15}/>Finished · {draft.pieces.length.toLocaleString()} pieces</>:draft?`${draft.pieces.length.toLocaleString()} pieces`:"Ready when you are"}</span><div><button disabled={!draft} aria-pressed={motionPaused} onClick={()=>setMotionPaused(v=>!v)}>{motionPaused?<Play size={16}/>:<Pause size={16}/>}<span>{motionPaused?"Resume":"Pause motion"}</span></button><button disabled={!draft||busy} onClick={()=>{setMotionPaused(false);setReplay(v=>v+1);}}><RotateCcw size={16}/><span>Replay</span></button><button aria-expanded={mobilePanel==="refine"} onClick={()=>{const show=mobilePanel!=="refine";setMobilePanel(show?"refine":"preview");if(show)requestAnimationFrame(()=>document.getElementById("creation-controls")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"}));}}><SlidersHorizontal size={16}/><span>{mobilePanel==="refine"?"Hide controls":"Refine"}</span></button></div></div>}<div className="generator-layout"><div id="creation-controls" className="generator-conversation">
 {setup?<BriefForm brief={brief} onChange={b=>{setBrief(b);setReview(null);}}/>:<><div className="brief-recap"><strong>{brief.idea}</strong><span>{brief.detail} detail · up to {brief.maxPieces.toLocaleString()} pieces</span><button disabled={busy} onClick={()=>setSetup(true)}>Edit brief</button></div>
 {scene&&!busy&&<details className="component-locks"><summary><LockKeyhole size={15}/>{locked.length?`${locked.length} components protected`:"Protect parts you already love"}</summary><p>Locked components keep their geometry and color. Revisions that overlap them are rejected.</p><div>{components.map(c=><label key={c}><Checkbox checked={locked.includes(c)} onCheckedChange={v=>setLocked(list=>v?[...list,c]:list.filter(x=>x!==c))}/>{c}</label>)}</div>{(manual.bricks.length>0||manual.erase.length>0)&&<p>{manual.bricks.length} edited bricks and {manual.erase.length} erased regions are also protected.</p>}</details>}
 <details className="design-history"><summary>Design history</summary><div className="generation-messages">{messages.slice(-6).map((m,i)=><div className={`generation-message message-${m.role}`} key={i}><span>{m.role==="you"?"YOU":"BRICKWORK"}</span><p>{m.text}</p></div>)}</div></details>
 {!busy&&<form className="generation-form" onSubmit={e=>{e.preventDefault();void run();}}><label htmlFor="generation-prompt">What would you like to change?</label><Textarea id="generation-prompt" rows={3} maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Give the tower a spiral staircase. Keep the dragon as it is."/><button className="button primary" type="submit" disabled={prompt.trim().length<3}><Send size={15}/>Update design</button></form>}</>}
 <AIConnection configured={configured} apiKey={apiKey} busy={busy} active={open} expanded={showConnection} onExpand={setShowConnection} setup={setup} budget={budget} onBudget={setBudget} onConnect={key=>{setApiKey(key);setShowConnection(false);setError("");setErrorCode("");if(setup)void run(false,key);}} onForget={()=>{setApiKey("");setBudget(null);}}/>
 <div className="repair-option"><div><label htmlFor="auto-repair">Auto-refine</label><p>Looks over the finished model and quietly fixes what it can.</p></div><Switch id="auto-repair" checked={autoRepair} disabled={busy} onCheckedChange={setAutoRepair}/></div>
 {busy&&<button className="button secondary" onClick={stop}><Square size={14}/>Stop and keep last draft</button>}
 {error&&<div className="creation-error" role="alert"><p>{error}</p>{!busy&&!budgetBlocked&&<button className="button secondary" onClick={()=>void run()}><RotateCcw size={14}/>Try again</button>}</div>}
 </div><div className="generation-preview"><div className="generation-preview-header"><span>{setup?"YOUR DESIGN BRIEF":busy?phase==="repair"?"REFINING":"LIVE DESIGN":draft?.name||"YOUR 3D BUILD"}</span>{busy&&<span><LoaderCircle size={13} className="spin"/>{shapeCount} shape definitions</span>}</div>
 {!setup&&<><div className="generation-canvas">{draft?assemblyPreview&&!busy?<AssemblyPlayer model={draft} compact onExit={()=>setAssemblyPreview(false)}/>:<Viewport arrivals={{epoch:replay,paused:motionPaused}} pieces={draft.pieces} length={draft.length} width={draft.width} height={draft.height} modelKey="live-creation" explode={0} stage={100000} selected={null} view={view} reset={0} rotate={false} onPick={()=>{}}/>:<div className="generation-empty"><span className="empty-stage-label">{busy?"THE FIRST PIECES ARE ON THEIR WAY":error?"GENERATION PAUSED":"YOUR NEXT CREATION"}</span><strong>{busy?brief.idea:error?"Your idea is still here.":"An open canvas."}</strong><p>{busy?"Waiting for the builder’s first geometry. Bricks will appear here as soon as it arrives.":error?error:"Start a design from your brief."}</p>{!busy&&<button className="button primary" onClick={()=>setSetup(true)}>Back to my brief<ArrowRight size={16}/></button>}</div>}</div><button className="generation-assembly" disabled={!draft||busy} aria-pressed={assemblyPreview} onClick={()=>setAssemblyPreview(v=>!v)}>{assemblyPreview?<><RotateCcw size={16}/>Back to live view</>:<><Play size={17} fill="currentColor"/>Play assembly<span>18 seconds</span></>}</button><div className="review-camera">{["perspective","front","top"].map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v}</button>)}</div></>}
 {previewError&&<p className="live-preview-error" role="status">Preview update: {previewError} The last visible draft is kept.</p>}{error&&<div className="stage-recovery" role="alert"><div><strong>{interrupted?"Your progress is kept.":draft&&scene?"Your design is kept.":"Let’s get your build going."}</strong><p>{error}</p></div>{!busy&&!budgetBlocked&&<button className="button secondary" onClick={()=>{if(errorCode==="AI_AUTH"||errorCode==="AI_NOT_CONNECTED"){setShowConnection(true);setMobilePanel("refine");requestAnimationFrame(()=>document.getElementById("creation-controls")?.scrollIntoView({block:"start",behavior:"auto"}));}else void run(Boolean(scene&&!interrupted&&(phase==="done"||phase==="review")));}}>{errorCode==="AI_AUTH"||errorCode==="AI_NOT_CONNECTED"?"AI settings":interrupted?"Continue design":scene&&(phase==="done"||phase==="review")?"Retry review":"Try again"}</button>}</div>}{busy&&<button className="mobile-stop button secondary" onClick={stop}><Square size={14}/>Stop and keep draft</button>}<div className={`generation-status ${draft&&!busy&&scene&&!setup?"is-finished":""}`} role="status">{busy?<LoaderCircle size={15} className="spin"/>:ready?<Check size={15}/>:<Sparkles size={15}/>}<p>{status||"Your brief is ready when you are."}</p>{budget&&<span className="live-budget">${budget.remaining.toFixed(2)} available · $10 limit</span>}{busy&&<span className="live-elapsed">{elapsed}s · {(draft?.pieces.length||0).toLocaleString()} bricks</span>}
 {draft&&!busy&&scene&&!setup&&<div className="review-actions finish-actions">{!ready&&<button className="button secondary" disabled={budgetBlocked} onClick={()=>void run()}><RotateCcw size={14}/>{interrupted?"Continue design":"Repair issues"}</button>}<button className="button secondary" disabled={interrupted||budgetBlocked} onClick={()=>void run(true)}><Eye size={14}/>Review again</button><button className="button primary" onClick={useBuild}>{ready?"Open in studio":"Keep as working draft"}<ArrowRight size={16}/></button></div>}</div>
 {draft&&!busy&&scene&&!setup&&<div className="generation-result">{interrupted&&<p className="unfinished-draft">Unfinished draft. Continue building before reviewing the complete design.</p>}<div><strong>{draft.pieces.length.toLocaleString()} pieces</strong><span>{(draft.length*.8).toFixed(1)} × {(draft.width*.8).toFixed(1)} × {(draft.height*.32).toFixed(1)} cm</span></div><details className="design-inspection"><summary>{ready?"Design checks passed":"Review design checks"}<span>{checks?.issues.length||0} geometry issues</span></summary><div className={`review-verdict ${ready?"passed":"needs-work"}`}><strong>{ready?"Digital checks passed":"Needs review"}</strong><span>{checks?.pass?"Support paths and size limits pass.":`${checks?.issues.length} geometry or brief checks need attention.`} {visualPassed?"Visual brief review passes.":"Visual brief review is incomplete or has concerns."}</span></div>
 {checks&&checks.issues.length>0&&<ul className="review-issues">{checks.issues.map(i=><li key={i}>{i}</li>)}</ul>}{review&&<div className="feature-review"><p>{review.summary}</p>{review.revision&&review.revision.status!=="not_requested"&&<div><span className={`feature-state ${review.revision.status}`}>{review.revision.status}</span><strong>Your requested change</strong><p>{review.revision.evidence}</p></div>}{review.features.map((f,i)=><div key={i}><span className={`feature-state ${f.status}`}>{f.status}</span><strong>{f.feature}</strong><p>{f.evidence}</p></div>)}</div>}{diff&&previous&&<p className="diff-summary">{diff.added} shapes added · {diff.changed} changed · {diff.removed} removed</p>}<p className="review-limit">Digital checks cover geometry, support paths and visible details. Physical strength, fit and hand access still need a test build.</p>
 </details></div>}
 </div></div>{setup&&<div className="brief-commit"><span>Up to {brief.maxPieces.toLocaleString()} pieces<small>{brief.detail==="signature"?"Signature":brief.detail==="balanced"?"Essential":"Detailed"} design</small></span><button className="button primary begin-design" disabled={brief.idea.trim().length<3||busy||configured===null&&!apiKey} onClick={()=>void run()}><Sparkles size={17}/>{configured===null&&!apiKey?"Checking connection…":configured||apiKey?scene?"Rebuild design":"Build my design":"Connect to build"}<ArrowRight size={17}/></button></div>}</DialogContent></Dialog>;
}
